add test task
Comediant24/apress-frontend_test_task pull request #1
Opened 2022-04-19 20:51 UTC by alenakono

Test task
Konovalova Alena

2022-04-22 05:39 UTC, Comediant24 commented
Привет!
Спасибо за выполненную работу! К реализации тестового есть несколько вопросов:

1. Почему весь js код находится в папке src/api ?
2. Нет системного подхода в наименование классов элементов. Применяются свйоства непосредственно к элементам. Есть разные системы и правила наименования классов. Один из стандартов отрасли является [БЭМ](https://ru.bem.info/).
3. Весь фичи реализованы одним коммитом. В разработке применяется подход когда различные фичи делаются одним или объединенной группой коммитов. Подробно можешь ознакомиться о хороших практиках [тут](https://habr.com/ru/company/otus/blog/537196/)

Что понравилось:
1. Хорошая реализация вставки продуктовых карт в дом дерево.
2. В целом код хорошо оформлен, но к некоторым моментам есть вопросы - о них написал в комментариях.
3. Используются семантичные теги.
4. Скрипт и стили правильно импортированы.

2022-04-22 05:39 UTC, Comediant24 requested changes

2022-04-22 05:39 UTC, Comediant24 commented on src/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap');
Почему решила использовать шрифты с гугл сервиса? Какие есть проблемы с этим решением?

2022-04-22 05:39 UTC, Comediant24 commented on src/style.css
> +body{
Задание стилей напрямую к элементу - плохая практика, если речь не идет о нормализации стилей

2022-04-22 05:39 UTC, Comediant24 commented on src/style.css
> +.button-red{
БЭМ селекторы используются вперемешку с обычными селекторами - только запутывает и такое труднее поддерживать.

2022-04-22 05:39 UTC, Comediant24 commented on src/style.css
> +    font-family: Montserrat;
При описании шрифтов не указаны альтернативные шрифты.

2022-04-22 05:39 UTC, Comediant24 commented on src/style.css
> +.wrapper{
Не вижу этого элемента с этим классом на странице. Лишний код - лишний объем который грузится на страницу.

2022-04-22 05:39 UTC, Comediant24 commented on src/api/products.js
> +    <img src="${content[key].img}" alt="item">
Обертка из `div` выглядит лишней. Все свойства можно описать непосредственно у тега `img`.

2022-04-22 05:39 UTC, Comediant24 commented on src/index.html
> +                <div class="popup__close">&#10006</div>
По своему поведению этот элемент кнопка, необходимо использовать семантичные теги для определения элементов.

2022-04-22 05:39 UTC, Comediant24 commented on src/api/products.js
> +    <button class="button button-cart cart__open">В корзину</button>
У `button` должен быть указан атрибут `type` - в таком случае можно предупредить некорректную обработку событий по клавише `Enter`

2022-04-23 19:48 UTC, alenakono commented
Здравствуйте! Спасибо большое за подробную обратную связь. Если честно, это мой первый опыт создания модального окна и работы с API. Определенно есть куда стремиться, возьму на вооружение информацию и все изучу.

2022-04-23 19:56 UTC, alenakono commented on src/api/products.js
> +    item.addEventListener('click', function () {
Для открытия  popup вместо назначения обработчика click на каждый товар, можно повесить единый обработчик на родительский элемент. Внутри обработчика проверять,  осуществляется клик внутри нашего блока или нет. Если да, всплывает popup

2022-04-23 19:58 UTC, alenakono commented on src/api/products.js
> +let content = API.products.splice(0, API.products.length);
Для удобства записи в дальнейшем при переборе

2022-04-23 19:58 UTC, alenakono commented on src/api/products.js
> +console.log(API.products);
Нет, в данном случае это не нужная информация, нужно было удалить эту строку.

2022-04-23 19:59 UTC, alenakono commented on src/api/products.js
> +    popupInfoOrder = document.querySelector('.popup-info__order'),
Поняла, спасибо! Изучу.

2022-04-23 20:09 UTC, alenakono commented on src/api/products.js
> +let cartOpenButton = document.querySelectorAll('.cart__open'),
Как я понимаю, использование var сейчас считается устаревшим, кроме случаев когда нужны свойства, присущие именно var.
Let может изменять свое значение в дальнейшем, константа остается неизменной.  Если я поменяю в этих случаях let на const, код не сломается, но изменить значение const будет нельзя

2022-04-23 20:12 UTC, alenakono commented on src/api/products.js
> +    popupOrder = document.getElementById('popup__order'),
Так как popupOrder и cartOrder в одном экземпляре на странице. Только мне следовало более уточняющее название для них сделать (на случай если будут еще всплывающие окна). 
Либо можно было каждому присвоить класс, но тогда нужно быть уверенным, что класс будет применяться один раз, так как querySelector покажет первый элемент, соответствующий поиску

2022-04-23 20:15 UTC, alenakono commented on src/api/products.js
> +    cartOrder.classList.remove('active');
Наверное можно сделать setTimeout(() => item.remove(), n), чтобы через n-ое время, например минуту блок удалялся.
Либо, чтобы при нажатии на кнопку подтверждения заказа "отправить", карточки товаров удалялись.

2022-04-23 20:22 UTC, alenakono commented on src/index.html
> +                        <input type="submit" value ="Отправить" class="button button-red popup-form__submit ">
В принципе, здесь можно было использовать button type = submit

2022-04-23 20:26 UTC, alenakono commented on src/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap');
Если честно, изначально так привыкла при обучении, так как там много бесплатных вариантов шрифтов. Хотя подключенные таким образом шрифты могут дольше подключаться или подключаться с задержкой, слететь

2022-04-23 20:38 UTC, alenakono commented on src/api/products.js
> +            titleCart = item.querySelector('.card__title'),
На этот счет пока нет идей

2022-05-06 14:36 UTC, closed without merging