Artem Pershin
Comediant24/apress-frontend_test_task pull request #2
Opened 2022-04-26 06:37 UTC by Sellich

2022-04-27 11:02 UTC, Comediant24 commented
Привет!
Спасибо за выполненную работу!

К реализации есть несколько вопросов:
1. Не совсем правильно используешь методологию БЭМ, если конечно вообще используешь ее. В каких то местах имена классов подобраны правильно, а в каких то непонятно какую систему использовал.
2. В идеале весь скрипт должен находится в js файлах, а импортироваться на страницу через `script src`.
3. Практически все элементы выполнены дивами. Важно использовать семантически верные теги.
4. Ухудшаешь перформанс вешая 20 обработчиков (по 10 на каждую кнопку на карточке товара).

Что понравилось
1. Импортируешь скрипт на страницу с атрибутом defer.
2. Хорошая реализация вставки продуктовых карт в дом дерево.
3. В целом код хорошо оформлен, но к некоторым моментам есть вопросы.

2022-04-27 11:02 UTC, Comediant24 requested changes

2022-04-27 12:32 UTC, Sellich commented
Здравствуйте. Большое спасибо за подробную обратную связь. Учту ошибки и
постараюсь не повторять их в будущем.

On Wed, Apr 27, 2022, 4:03 PM Iurii Bairamukov ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/index.js
> <https://github.com/Comediant24/apress-frontend_test_task/pull/2#discussion_r859587293>
> :
>
> > +      popUpBasket.classList.remove('invisibility')
> +      popUpBasket.querySelector('.info__info_title').innerHTML =
> +         document.querySelectorAll(".main__item")[i].querySelector('.item__info_name').innerHTML;
> +
> +      popUpBasket.querySelector('.info__info_price').innerHTML =
> +         document.querySelectorAll(".main__item")[i].querySelector('.item__info_price').innerHTML;
> +
> +      popUpBasket.querySelector('.basket_img').src =
> +         document.querySelectorAll(".main__item")[i].querySelector('.img').src;
> +      setTimeout(() => { popUpBasket.classList.add('invisibility') }, 1000)
> +   });
> +}
> +
> +
> +closeButton.addEventListener("click", function () { popUpOrder.classList.add('invisibility') })
> +submitButton.addEventListener("click", function () { console.log('click') })
>
> В консоли при загрузке страницы ошибка, так как данного элемента нет на
> странице.
> Весь отлаживающий код должен быть удален.
> ------------------------------
>
> In src/index.js
> <https://github.com/Comediant24/apress-frontend_test_task/pull/2#discussion_r859591274>
> :
>
> > +for (let i = 0; i < orderButton.length; i++) {
> +   orderButton[i].addEventListener("click", function () {
>
> Сейчас у тебя 10 карточек и на каждую кнопку "Заказать" у тебя
> навешивается свой обработчик события. Если будет 100 карточек, то будет 100
> обработчиков. Это повлияет на перформанс.
> Есть идеи как это можно улучшить?
> ------------------------------
>
> In src/index.js
> <https://github.com/Comediant24/apress-frontend_test_task/pull/2#discussion_r859593019>
> :
>
> > +      popUpOrder.querySelector('.popup__order_title').innerHTML =
> +         document.querySelectorAll(".main__item")[i].querySelector('.item__info_name').innerHTML;
> +
> +      popUpOrder.querySelector('.info__left_price').innerHTML =
> +         document.querySelectorAll(".main__item")[i].querySelector('.item__info_price').innerHTML;
> +
> +      popUpOrder.querySelector('.order_img').src =
> +         document.querySelectorAll(".main__item")[i].querySelector('.img').src;
>
> При кликах у тебя код будет проделывать трижды одну и туже работу, а
> именно искать все элементы main__item. Это повлияет на перфоманс. Есть
> идеи, как это можно улучшить?
> ------------------------------
>
> In src/index.js
> <https://github.com/Comediant24/apress-frontend_test_task/pull/2#discussion_r859594337>
> :
>
> > +for (let i = 0; i < inBasketButton.length; i++) {
> +   inBasketButton[i].addEventListener("click", function () {
> +      popUpBasket.classList.remove('invisibility')
> +      popUpBasket.querySelector('.info__info_title').innerHTML =
> +         document.querySelectorAll(".main__item")[i].querySelector('.item__info_name').innerHTML;
> +
> +      popUpBasket.querySelector('.info__info_price').innerHTML =
> +         document.querySelectorAll(".main__item")[i].querySelector('.item__info_price').innerHTML;
> +
> +      popUpBasket.querySelector('.basket_img').src =
> +         document.querySelectorAll(".main__item")[i].querySelector('.img').src;
>
> Предыдущие два вопроса также относятся и к этому участку кода.
> ------------------------------
>
> In src/index.html
> <https://github.com/Comediant24/apress-frontend_test_task/pull/2#discussion_r859596233>
> :
>
> > +        <script type="module">
> +            import API from "./API.js"
> +            document.querySelector('.main').innerHTML = API.products.map(el =>
> +                  `<div class="main__item" >
> +                   <div class="item__img">
> +                     <img src=${el.img} alt="" class="img">
> +                  </div>
> +                  <div class="item__info">
> +                     <div class="item__info_name">
> +                        ${el.title}
>
> Когда браузер будет парсить страницу он упрется в это js код и дальнейшая
> отрисовка страницы остановится - это может повлечь неприятные последствия в
> случае, например, ошибки в коде или ошибки на стороне API страницы не
> отрисуется до конца и это плохо повлияет на портал и юзера.
>
> Обычно, когда ждут ответа от апи на странице размещают какой нибудь лоадер
> (крутилку) и после отрисовки страницы и ответа от апи удаляют его и на его
> место размещают контент полученный от апи.
> ------------------------------
>
> In src/index.html
> <https://github.com/Comediant24/apress-frontend_test_task/pull/2#discussion_r859598696>
> :
>
> > +         <div class="header__title">
> +            МАГАЗИН N
> +         </div>
> +         <div class="header__basket">
> +            Корзина
> +         </div>
>
> Для данных элементов необходимо применять семантичные теги.
> Текстовые элементы должны быть размечены через теги параграфов и
> заголовков, кнопки через button и т.д.
> О семантике https://htmlacademy.ru/blog/articles/semantics
> ------------------------------
>
> In src/index.html
> <https://github.com/Comediant24/apress-frontend_test_task/pull/2#discussion_r859600770>
> :
>
> > +      <div class="popup__order invisibility">
> +         <div class="popup__order_title">
> +
> +         </div>
> +         <div class="popup__order_info">
>
> БЭМ подразумевает, что все элементы блока должны быть размечены внутри
> него. По всей видимости данные элементы у тебя должны быть обернуты в блок
> popup.
> ------------------------------
>
> In src/index.html
> <https://github.com/Comediant24/apress-frontend_test_task/pull/2#discussion_r859601596>
> :
>
> > +         <div class="popup__order_title">
> +
> +         </div>
>
> Опять же в таких местах должны быть использованы семантичные теги. Тут и
> далее везде.
> ------------------------------
>
> In src/index.html
> <https://github.com/Comediant24/apress-frontend_test_task/pull/2#discussion_r859603633>
> :
>
> > +                  <button class="btn__basket btn">
> +                     В корзину
> +                  </button>
> +               </div>
> +            </div>
> +            <div>
> +
> +            </div>
> +         </div>`
> +                        ).join('')
> +         </script>
> +         <script defer src="index.js"></script>
> +      </main>
> +
> +      <div class="popup__order invisibility">
> +         <div class="popup__order_title">
>
> В этом месте становится не понятно какую методологию по названию классов
> ты начал применять.
> Сейчас у тебя название класса указана в нотации блок__элемент_модификатор,
> хотя этот элемент точно относится к элементу и модификатором быть не может.
>
> https://ru.bem.info/methodology/quick-start/#%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%BD%D0%B8%D0%B5
> ------------------------------
>
> In src/index.html
> <https://github.com/Comediant24/apress-frontend_test_task/pull/2#discussion_r859604321>
> :
>
> > +               </div>
> +            </div>
> +            <div>
> +
> +            </div>
> +         </div>`
> +                        ).join('')
> +         </script>
> +         <script defer src="index.js"></script>
> +      </main>
> +
> +      <div class="popup__order invisibility">
> +         <div class="popup__order_title">
> +
> +         </div>
> +         <div class="popup__order_info">
>
> И тут тоже проблема с неймингом.
> ------------------------------
>
> In src/index.html
> <https://github.com/Comediant24/apress-frontend_test_task/pull/2#discussion_r859604650>
> :
>
> > +            <div class="order__info_left">
> +               <div class="info__left_img">
> +                  <img src="" alt="" class="order_img">
> +               </div>
> +               <div class="info__left_price">
> +                  Price
> +               </div>
> +             [...]

2022-04-28 13:49 UTC, Comediant24 commented
https://learn.javascript.ru/bubbling-and-capturing

2022-05-06 14:35 UTC, closed without merging