Выполненное ТЗ на React
Comediant24/apress-frontend_test_task pull request #9
Opened 2023-02-14 23:39 UTC by Tomiloff

Юрий, добрый день!
Проверьте, пожалуйста, работу.

Прилагаю ссылку для просмотра развёрнутой версии сайта на github-pages:
https://tomiloff.github.io/apress-frontend_test_task

Адаптация под мобильную версию также сделана.

Спасибо, что ознакомились с ПР.
Буду очень благодарен Вам за обратную связь.

2023-02-16 14:45 UTC, Comediant24 requested changes
Привет!
Спасибо за выполненную работу.

К реализации есть несколько замечаний:
* В твоей реализации все картинки загружены через `img`. Различие состоит в том, что картинки несущие смысловую нагрузку или же каким-либо образом относящиеся к содержанию страницы следует вставлять тегом img (картинки в тексте, баннеры, картинки слайдера, аватарки и тд). Все остальное (просто элементы оформления: различного рода разделители, маркеры, фоны и тд.) следует вставлять в дизайн используя background-image. Это очищает разметку и дает для индексации нужные картинки.
* Протекают стили по модулям. Для стилизации используешь теги. В таком случае стили могут себя повести неожиданно.
* Используется не корректная разметка. Если проверить разметку через валидатор w3c, то можно найти будет много ошибок. В основном это неправильное использование тегов в контексте другово тега.
* На странице сразу несколько видов таблиц - для декстопа и мобилы. При 10 товаров это не насет вреда перформансу, при 100 будет ощутимо. К тому же если добавить поиске по товарам и сортировку, то наличие двух таблиц будет мешать этому функционалу.

Что понравилось:

* Используются семантические теги
* Компонент попапа организован правильно, его можно масштабировать в будущем.
* Организация ассетов имеют понятную систему.

2023-02-16 14:45 UTC, Comediant24 commented on src/common/TopTable/Header/Header.module.css
> +  z-index: 1000;
В больших проектах z-index свойств на одной странице могут быть от 10 и больше. Когда присваивается `z-index` необдуманно это может привести к неприятным неожиданностям в будущем.

2023-02-16 14:45 UTC, Comediant24 commented on src/common/TopTable/Table/Table.module.css
> +}
Какие способы организации CSS ты используешь в своей реализации тестового?

2023-02-16 14:45 UTC, Comediant24 commented on src/features/TopTable/ModalWrapper/ModalProduct/ModalProductContent/ModalProductContent.jsx
> +      </div>
Лишняя обертка над `img`. Можно обойтись без неё.

2023-02-16 14:45 UTC, Comediant24 commented on src/components/TopTable/Buttons/ModalBtn/ExitButton.jsx
> +    </div>
Лишняя обертка над `img`. Можно обойтись без неё.

2023-02-16 14:45 UTC, Comediant24 commented on src/features/TopTable/Table/MobileTbody/MobileTbody.jsx
> +            .join("/");
Есть более элегантное решение получения даты из макета используя встроенное api браузера. Сможешь найти?

2023-02-16 14:45 UTC, Comediant24 commented on src/features/TopTable/Table/MobileTbody/MobileTbody.jsx
> +        <td>{Number(count) > 0 ? <AvailableInStock /> : <OutOfStock />}</td>
`Number(count)` нет необходимости сравнивать с 0.
`count` по сути булевое значение.

2023-02-16 14:45 UTC, Comediant24 commented on src/features/TopTable/Table/MobileTbody/MobileTbody.module.css
> +}
Стили для td протекает по всем тегам td на странице. Есть идеи как это исправить?
![image](https://user-images.githubusercontent.com/63135211/219391182-c709ea6d-6a53-4684-934e-7d17ab0f87e1.png)

2023-02-16 14:45 UTC, Comediant24 commented on src/features/TopTable/Table/Tbody/Product/Product.jsx
> +            .join("/");
Код выглядит утилитарным и и спользуется в двух компонентах. Такие участки нужно выносить в общие утилиты.

2023-02-16 17:46 UTC, Tomiloff commented on src/features/TopTable/Table/MobileTbody/MobileTbody.jsx
> +        <td>{Number(count) > 0 ? <AvailableInStock /> : <OutOfStock />}</td>
Пофиксил

2023-02-16 17:55 UTC, Tomiloff commented on src/features/TopTable/Table/Tbody/Product/Product.jsx
> +            .join("/");
Пофиксил

2023-02-16 18:16 UTC, Tomiloff commented on src/components/TopTable/Buttons/ProductBtn/ProductBtn.jsx
> +      <p>{name}</p>
Пофиксил

2023-02-16 18:31 UTC, Tomiloff commented on src/common/TopTable/Header/Header.module.css
> +  z-index: 1000;
Что то я совсем перегнул))
Пофиксил

2023-02-16 21:11 UTC, Tomiloff commented on src/features/TopTable/Table/MobileTbody/MobileTbody.module.css
> +}
Пофиксил

2023-02-16 21:35 UTC, Tomiloff commented on src/common/TopTable/Table/Table.module.css
> +}
Переделал сейчас организацию CSS по БЭМ)

2023-02-17 17:39 UTC, Tomiloff commented on src/components/TopTable/Buttons/ModalBtn/ExitButton.jsx
> +        <img src={crossIcon} alt="crossIcon" />
Пофиксил

2023-02-17 17:51 UTC, Tomiloff commented on src/components/TopTable/Buttons/ModalBtn/ExitButton.jsx
> +    </div>
Пофиксил

2023-02-17 18:05 UTC, Tomiloff commented on src/features/TopTable/ModalWrapper/ModalProduct/ModalProductContent/ModalProductContent.jsx
> +      </div>
Пофиксил

2023-02-17 18:39 UTC, Tomiloff commented on src/common/TopTable/Table/Table.jsx
> +          <MobileTbody key={id} id={id} name={name} createdAt={createdAt} price={price} count={count} description={description} imageUrl={imageUrl} url={url} openModal={openModal} />
Пофиксил

2023-02-18 06:51 UTC, Tomiloff commented on src/features/TopTable/Table/MobileTbody/MobileTbody.jsx
> +            .join("/");
Пофиксил

2023-02-18 12:45 UTC, Tomiloff commented on src/common/TopTable/Table/Table.jsx
> +      })}
Пофиксил

2023-02-20 18:36 UTC, Tomiloff commented
Юрий, привет!
Спасибо большое за ревью кода.

Провёл рефакторинг и добавил функционал из обновлённого ТЗ:
- Поиск по названию товара;
- Закрытие попап по оверлею;
- У попап описание на 5 строк, остальной текст обрезается троеточием ...

https://tomiloff.github.io/apress-frontend_test_task

Функционал, который в процессе доработки: 
- Сортировка по дате создания и цене

2023-07-31 10:47 UTC, closed without merging